import React from "react";
import Head from "next/head";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "config";
import Layout from "components/layout";

function MyApp({ Component, pageProps }) {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </React.Fragment>
  );
}

export default MyApp;
